[project]
name = "aircraft"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.11.13",
    "fastapi>=0.115.11",
    "pydantic-settings>=2.8.1",
    "redis>=5.2.1",
    "uvicorn>=0.34.0",
]
